<a href="https://colab.research.google.com/github/moniquelin/ml-zoomcamp/blob/main/homework/hw_week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Machine Learning Zoomcamp Homework - Week 1

In [1]:
# libraries

import numpy as np
import pandas as pd

#### Question 1

In [2]:
# version of numpy
np.__version__

'1.19.5'

#### Question 2

In [3]:
# version of pandas
pd.__version__

'1.1.5'

#### Question 3

In [4]:
# getting the data

!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2021-09-13 11:44:23--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv.2’

data.csv.2          100%[===================>]   1.41M  --.-KB/s    in 0.06s   

2021-09-13 11:44:23 (23.8 MB/s) - ‘data.csv.2’ saved [1475504/1475504]



In [6]:
data = pd.read_csv('data.csv')
data.head()

Make       Model  Year  ... city mpg  Popularity   MSRP
0  BMW  1 Series M  2011  ...       19        3916  46135
1  BMW    1 Series  2011  ...       19        3916  40650
2  BMW    1 Series  2011  ...       20        3916  36350
3  BMW    1 Series  2011  ...       18        3916  29450
4  BMW    1 Series  2011  ...       18        3916  34500

[5 rows x 16 columns]

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

In [7]:
data['Make'].unique()

array(['BMW', 'Audi', 'FIAT', 'Mercedes-Benz', 'Chrysler', 'Nissan',
       'Volvo', 'Mazda', 'Mitsubishi', 'Ferrari', 'Alfa Romeo', 'Toyota',
       'McLaren', 'Maybach', 'Pontiac', 'Porsche', 'Saab', 'GMC',
       'Hyundai', 'Plymouth', 'Honda', 'Oldsmobile', 'Suzuki', 'Ford',
       'Cadillac', 'Kia', 'Bentley', 'Chevrolet', 'Dodge', 'Lamborghini',
       'Lincoln', 'Subaru', 'Volkswagen', 'Spyker', 'Buick', 'Acura',
       'Rolls-Royce', 'Maserati', 'Lexus', 'Aston Martin', 'Land Rover',
       'Lotus', 'Infiniti', 'Scion', 'Genesis', 'HUMMER', 'Tesla',
       'Bugatti'], dtype=object)

In [20]:
data.groupby('Make').mean().loc['BMW']

Year                 2014.347305
Engine HP             326.907186
Engine Cylinders        5.958084
Number of Doors         3.161677
highway MPG            29.245509
city mpg               20.739521
Popularity           3916.000000
MSRP                61546.763473
Name: BMW, dtype: float64

#### Question 4

In [27]:
data[data['Year'] >= 2015].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5995 entries, 32 to 11902
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               5995 non-null   object 
 1   Model              5995 non-null   object 
 2   Year               5995 non-null   int64  
 3   Engine Fuel Type   5995 non-null   object 
 4   Engine HP          5944 non-null   float64
 5   Engine Cylinders   5987 non-null   float64
 6   Transmission Type  5995 non-null   object 
 7   Driven_Wheels      5995 non-null   object 
 8   Number of Doors    5990 non-null   float64
 9   Market Category    4671 non-null   object 
 10  Vehicle Size       5995 non-null   object 
 11  Vehicle Style      5995 non-null   object 
 12  highway MPG        5995 non-null   int64  
 13  city mpg           5995 non-null   int64  
 14  Popularity         5995 non-null   int64  
 15  MSRP               5995 non-null   int64  
dtypes: float64(3), int64(5

#### Question 5

In [42]:
# average Engine HP

mean_hp_before = data['Engine HP'].mean()
mean_hp_before

249.38607007176023

In [40]:
# fill missing values with mean
new_engine_hp = data['Engine HP'].fillna(engine_hp_mean)

In [39]:
# check if there's any missing values left
new_engine_hp.isna().unique()

array([False])

In [44]:
# check new mean
mean_hp_after = new_engine_hp.mean()
print("Mean before filling missing values:", round(mean_hp_before))
print("Mean after filling missing values:", round(mean_hp_after))

Mean before filling missing values: 249
Mean after filling missing values: 249


#### Question 6

In [46]:
# Select all the "Rolls-Royce" cars from the dataset
rolls_royce = data[data['Make'] == 'Rolls-Royce']

# Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
rolls_royce = rolls_royce[['Engine HP', 'Engine Cylinders', 'highway MPG']]

In [51]:
# drop all duplicated rows
rr_no_dups = rolls_royce.drop_duplicates()
rr_no_dups

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [55]:
# get the numpy array
X = rr_no_dups.to_numpy()
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [57]:
# matrix-matrix multiplication between the transpose of X and X
XTX = np.matmul(X.T,X)  # X.T@X
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [62]:
# sum of elements in inverse of XTX
XTX_inv = np.linalg.inv(XTX)
np.sum(XTX_inv)

0.032212320677486125

#### Question 7

In [63]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]

matrix1 = XTX_inv@X.T
w = matrix1@y
w

array([ 0.19989598, 31.02612262, 31.65378877])